apiVersion: v1
kind: Service
metadata:
  name: devops-spring-service
spec:
  type: NodePort
  selector:
    app: devops-spring-app
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8082
